---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: skyline
    driver_config:
      require_chef_omnibus: true
      box: chef/debian-7.6
      box_url: https://vagrantcloud.com/chef/boxes/debian-7.6/versions/1/providers/virtualbox.box
      customize:
        memory: 1024
        cpus: 1

suites:
  - name: default
    driver_config:
      network:
        - ["private_network", {ip: "33.33.33.10"}]
    run_list:
      - recipe[skyline::default]
    attributes:
